DataBiosphere/cbas-ui

src/pages/PreviousRuns.js
src/pages/SavedWorkflows.js
src/pages/SubmitWorkflow.js

Closes https://broadworkbench.atlassian.net/browse/BW-1377

BW-1377 Remove workflow url and inputs from Saved Workflows and Previous Runs

---

.github/workflows/publish.yml

Closes https://broadworkbench.atlassian.net/browse/BW-1427

[BW-1427] Update Github workflow action publish.yml to update image version in cromwhelm

---

src/pages/PreviousRuns.js
src/pages/PreviousRuns.test.js

Closes https://broadworkbench.atlassian.net/browse/WM-1449

[WM-1449] Display last_modified_timestamp in Previous Runs page

---

src/components/StepButtons.js

They're not as rounded on the edges as I would like, but they're something.

[WM-1581] Dots to triangles

---

src/libs/ajax.js
src/pages/SavedWorkflows.js
src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js
src/pages/SubmissionDetails.js
src/pages/SubmissionDetails.test.js
src/pages/SubmitWorkflow.js

WM-1574, WM-1575: Support workflow versions

---

src/pages/SubmissionConfig.js

Closes https://broadworkbench.atlassian.net/browse/WM-1638

[WM-1638] Correctly display the number of workflows to be launched

---

.github/workflows/publish.yml

https://broadworkbench.atlassian.net/browse/WM-1629

[WM-1629] Add AppSec Trivy action

---

src/pages/RunDetails.js
src/pages/RunDetails.test.js

* Rename 'Run Details' page to 'Workflow Details'
* Remove extra status line in page

WX-912 Fix bugs in workflow details page

---

src/pages/SavedWorkflows.js

Screen as viewed in Monitor
------
Screen as viewed in 14" laptop
------
Shrinking screen
Closes https://broadworkbench.atlassian.net/browse/WM-1723

[WM-1723] Workflow name in Saved Workflows list is not truncated when window shrinks 

---

src/components/submission-common.js
src/components/submission-common.test.js
src/pages/SubmissionDetails.js
src/pages/SubmissionHistory/SubmissionHistory.js

Closes https://broadworkbench.atlassian.net/browse/WM-1717

[WM-1717] Display correct duration for Run Set in Submission Details page

---

src/libs/ajax.js
src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js
src/pages/ViewWorkflowScriptModal.js
src/pages/ViewWorkflowScriptModal.test.js

Screenshots:
-------------------
Closes https://broadworkbench.atlassian.net/browse/WM-1724

[WM-1724] View workflow script in modal

---

src/components/ConfigOverridesWarning.js
src/libs/browser-storage.js
src/libs/config.js
src/libs/state.js
src/pages/Main.js
src/pages/SubmitWorkflow.js

Feature flag: `configOverridesStore.set({ isFindWorkflowEnabled: true })`
Closes https://broadworkbench.atlassian.net/browse/WM-1695

[WM-1695] Find Workflow card enabled by feature flag

---

src/pages/RunDetails.js
src/pages/RunDetails.test.js

WX-956 Add workflow engine is to run details page

---

src/libs/ajax.js
src/pages/FindWorkflow/FindWorkflowModal.js
src/pages/FindWorkflow/FindWorkflowModal.test.js
src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js

Method loaded into the config page after selecting:
Method present in workflow cards list after importing:

[WM-1744] First WARP workflow in the UI

---

src/components/InputsTable.js
src/components/StructBuilder.js
src/components/submission-common.js
src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js

It leads the user down to the inner part of the struct where the warning originates

[WM-1815] struct builder inputs warnings

---

src/components/submission-common.js

should be merged *after* WM-1815

[WM-1844] struct builder source is read-only

---

src/components/InputsTable.js
src/components/StructBuilder.js
src/components/submission-common.js
src/libs/utils.js
src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js

Warning messages for newly created method. There is also a tooltip now indicating there are missing inputs for disabled submit button
Warning message for struct input and Use Struct Builder option
Warning messaged for required inputs in a struct
Closes https://broadworkbench.atlassian.net/browse/WM-1841

[WM-1841] Warning messages are displayed next to required inputs for new method

---

src/pages/SubmissionConfig.js
src/pages/SubmissionConfig.test.js

Tiny PR for adding a "back to workflows" button to the Submission Config page, that links back to the root page.

[WM-1753] Back to Workflows Button

---

src/pages/FindWorkflow/FindWorkflowModal.js
src/pages/FindWorkflow/FindWorkflowModal.test.js

Closes https://broadworkbench.atlassian.net/browse/WM-1924

[WM-1924] Tag WARP workflows to specific Github tags

---

src/components/RecordsTable.js
src/components/RecordsTable.test.js

All data types are rendered as expected:
https://github.com/DataBiosphere/cbas-ui/assets/16748522/845eb784-bb39-4aa5-94cc-e66ee99c0d22
Closes https://broadworkbench.atlassian.net/browse/WM-1975

[WM-1975] Render Boolean and JSON objects properly in Select Data tab

---

package.json
src/components/InputsTable.js
src/components/InputsTable.test.js
src/components/StructBuilder.js
src/components/StructBuilder.test.js
src/components/input.js
src/components/table.js
src/libs/style.js
src/pages/SubmissionConfig.js

https://github.com/DataBiosphere/cbas-ui/assets/67511512/01c3a9d3-1b53-4db8-a04c-20a6ce10a834

[WM-1949] Searchable Inputs

---

src/libs/ajax.test.js

Closes https://broadworkbench.atlassian.net/browse/WM-2010

[WM-2010] Add state for consumer side contract test for POST /methods endpoint

---

src/libs/ajax.test.js

Closes https://broadworkbench.atlassian.net/browse/WM-2010

[WM-2010] Check for UUID regex in POST /method endpoint contract test 

---

src/libs/ajax.js
src/libs/ajax.test.js

Closes https://broadworkbench.atlassian.net/browse/WM-2182

[WM-2182] CBAS UI passes auth header to CBAS when making requests
