Dockerfile
A new image containing this change has been pushed to GCR: [hello-world-ui-3](https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/us/terra-batch-analysis-ui?project=broad-dsp-gcr-public)
I tested it by creating Cromwell app in Dev environment and then upgrading the helm charts with the reverse proxy changes along with change that [updates the UI image to hello-world-ui-3](https://github.com/broadinstitute/cromwhelm/pull/36).
UI deployment with latest docker image:
UI now loads at `https://leonardo.dsde-dev.broadinstitute.org/proxy/google/v1/apps/terra-dev-e64f6eae/terra-app-7312934b-752c-4a89-8812-82fe9f9d1536/cromwell-service/batch-analysis-ui/`
Closes https://broadworkbench.atlassian.net/browse/BW-1266
=> BW-1266 Make UI proxy aware

public/config.json, src/components/HelloWorld.js, src/index.js, src/libs/ajax.js, src/libs/browser-storage.js, src/libs/config.js, src/libs/react-utils.js, src/libs/state.js, src/libs/utils.js, src/pages/Main.js
Lots of copy/paste from terra-ui to bootstrap. 
TODOs:
- Confirmed: works great.
- To be completed in [BW-1283](https://broadworkbench.atlassian.net/browse/BW-1283), if necessary.
Example running locally:
Note for reviewers: everything in `/src/libs/*` was copied across sections from the terra-ui files with the same names. It's probably a good idea to make sure I kept the spirit of the files and the copy/paste isn't horrible, but the actual logic is presumably good on account of its status within terra-ui
=> BW-1245: CBAS status element bootstrap

src/components/input.js, src/libs/ajax.js, src/pages/SubmitWorkflow.js, src/pages/WorkflowInputs.js
Note to reviewers: `TextInput` in `input.js` is copied from Terra UI
Testing: Local against local CBAS with Chris' changes from [PR #33](https://github.com/DataBiosphere/cbas/pull/33)
Screenshot of what the new inputs page looks like. The placeholders are added to let user know what is the expected structure of input:
After filling up the fields:
Successful response from CBAS after submitting the workflow:
Closes https://broadworkbench.atlassian.net/browse/BW-1342
=> BW-1342 Support for passing entity field and ID to CBAS

src/libs/ajax.js, src/pages/PreviousRuns.js, src/pages/SavedWorkflows.js, src/pages/SubmitWorkflow.js
Screenshots from local testing:
Since CBAS doesn't store workflow names yet, the decision made was to show Run ID for now ([see Slack thread](https://broadinstitute.slack.com/archives/G01CVT4GJ8H/p1663346166577329))
=> [BW-1376] Add workflow url and workflow inputs back

src/libs/ajax.js, src/pages/PreviousRuns.js, src/pages/workspaces/workspace/jobHistory/WorkflowDashboard.js
This PR creates links from the Previous Runs page to each workflow's dashboard, and back. 
It's a little confusing because the UUID you click on to get to the dashboard is the CBAS run id, and the UUID in the URL for the dashboard is the engine id (Cromwell workflow id). Given that these pages are about to change, I decided to leave it as-is until the dust settles. If we decide on a final destination for URL structure before this PR merges I am happy to update it.
=> WX-831 Navigate to and from workflow dashboard

src/pages/SubmissionDetails.js
this PR removes a duplicated header on the Submission Details page. The duplicate got there during a confusing merge conflict resolution.
Before:
After:
=> [WM-1580] remove extra submission details header

src/pages/SubmissionConfig.js
When there is no records found for record type, instead of showing a blank screen users will see below message (just like we show for Select data tab)
Closes https://broadworkbench.atlassian.net/browse/WM-1651
=> [WM-1651] Display message for Inputs tab when no records are available 

src/components/submission-common.js, src/pages/SubmissionDetails.js, src/pages/SubmissionHistory/SubmissionHistory.js
Below screenshot (from Submission Details) shows that auto refreshing happens as long as there is a run in non-terminal state. Once all runs reach terminal state the auto refreshing stops. Same logic applies to Submission History page. 
Note: I had updated the timeout to be 1 second for testing purposes as workflows usually fail within 1 minute. console.log statements have also been removed
Closes https://broadworkbench.atlassian.net/browse/WM-1653
=> [WM-1653] Auto refresh Submission History & Details pages

src/components/submission-common.js, src/pages/SubmissionConfig.js, src/pages/SubmissionConfig.test.js
Tested changes locally:
If any **required** input has a missing attribute a warning icon appears next to it in table. Inputs tab itself also has warning icon next to it and Submit button is disabled. Once user selects attributes for such inputs, the icons disappear and when all errors have been resolved icon next to Input tab also disappears and Submit button is enabled.
`assemble_refbased` workflow has 2 required inputs that are missing attributes:
Selecting attribute for 1 required input makes warning icon next to it disappear. Input tab has warning icon next to it.
All required inputs have attributes and warning icon next to Inputs tab disappears. Submit is enabled (since I have also selected data row).
Tooltip for warning icon:
Closes …
=> [WM-1659] Display warning icon if attribute is missing for required input

src/components/submission-common.js, src/libs/utils.js, src/libs/utils.test.js
Fixes arrays to no longer assume that the inner values must be primitives.
Stowaway changes which seemed useful to add in and took not much extra time:
- Updating optional type names from `String (optional)` to `String?`, to match how WDL displays them.
- Updating optional input font to italic on the input name and type, just like in Terra UI
Examples, including showing the table_map input now rendering correctly:
=> WM-1668: Fix type names and italicize optionals

src/components/submission-common.js, src/pages/SubmissionConfig.js, src/pages/SubmissionConfig.test.js
This PR fixes the behavior mentioned in the ticket. 
Before: The payload being sent for input switched to "None" source included `parameter_value`
```
{
"input_name": "fetch_sra_to_bam.Fetch_SRA_to_BAM.docker",
"input_type": {
"type": "optional",
"optional_type": {
"type": "primitive",
"primitive_type": "String"
}
},
"source": {
"type": "none",
"parameter_value": "quay.io/broadinstitute/ncbi-tools:2.10.7.10"
}
}
```
Now
```
{
"input_name": "fetch_sra_to_bam.Fetch_SRA_to_BAM.docker",
"input_type": {
"type": "optional",
"optional_type": {
"type": "primitive",
"primitive_type": "String"
}
},
"source": {
"type": "none"
}
}
```
Closes https://broadworkbench.atlassian.net/browse/WM-1667
=> [WM-1667] Don't submit parameter_value when input source is changed to None

public/index.html
Tab and the spinner (not in the screenshot as it was hard to capture it) will reference to Workflows
Closes https://broadworkbench.atlassian.net/browse/WM-1720
=> [WM-1720] Rename "Batch Analysis" to "Workflows"

src/pages/SubmissionConfig.js, src/pages/SubmissionDetails.js, src/pages/SubmissionHistory/SubmissionHistory.js, src/pages/SubmitWorkflow.js
Based on the [conversation with Sara on Slack](https://broadinstitute.slack.com/archives/G01CVT4GJ8H/p1676579460275039), it was decided to rename the title to `Run workflows...` instead of `Submit workflows...` and keep it consistent across all pages. The landing page banner has also been added:
Closes https://broadworkbench.atlassian.net/browse/WM-1721
=> [WM-1721] Change banner title to "Run Workflows with Cromwell"

src/components/submission-common.js, src/pages/SubmissionConfig.js, src/pages/SubmissionConfig.test.js
This is now the outcome when a preloaded workflow is missing a data table value:
=> WM-1729: Better tooltip for missing attribute

package.json, src/components/submission-common.js, src/pages/SubmissionDetails.js, src/pages/SubmissionDetails.test.js, src/pages/SubmissionHistory/SubmissionHistory.js
Screenshots show the duration column when first submitted, after a minute, and after 2 minutes. Both the run durations and run set durations give the correct time when being auto-refreshed.
=> [WM-1755] Fix auto-refresh on Submission Details page

src/pages/SubmissionConfig.js
- Elements on the submit modal are no longer enabled once submit is clicked.
- User cannot close the submit modal when submit is clicked.
- `Submit` changes to `Submitting...` when submit is clicked.
=> Acknowledge submission within modal

src/components/job-common.js
Ticket [WX-953](https://broadworkbench.atlassian.net/browse/WX-953).
Mapped all status enums that exist in `cromwell/core/src/main/scala/cromwell/core/ExecutionStatus.scala` to a reasonable user-facing state. Now, no enumerated statuses will be considered 'unknown'.
Tested by using my eyeballs on a local cbas-ui running a workflow.
[WX-953]: https://broadworkbench.atlassian.net/browse/WX-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix 'Unexpected Status' on Workflow Details page

src/pages/RunDetails.js, src/pages/workspaces/workspace/jobHistory/CallTable.js
I removed the call caching related bits from the components the user sees, but left the now-unused CallCachingWizard in place since we'll be enabling call caching sometime in the near future. 
Note, the Links column is empty in this screenshot but contains stuff if the task fails.
=> WX-957 Remove call cache result column

src/components/submission-common.js, src/components/submission-common.test.js, src/pages/SubmissionConfig.test.js
When WDS and CBAS is decoupled, the app type for WDS will no longer be `CROMWELL`. Hence it will be better to have this configurable and only update the config value when that happens.
Closes https://broadworkbench.atlassian.net/browse/WM-1763
=> [WM-1763] Make `appType` when resolving WDS proxy url configurable 

src/components/HelpfulLinksBox.js, src/components/submission-common.js, src/pages/SubmissionConfig.js
For 3 Covid-19 workflows the Have Questions box will display below 3 links:
For all other workflows only this link will be displayed:
Closes https://broadworkbench.atlassian.net/browse/WM-1837
=> [WM-1837] Provide Covid-19 tutorial links for user in Submission Config page

src/components/common.js, src/pages/RunDetails.js
Fixed an issue with a clipboard button in the Workflow Details page where it couldn't receive click events. [WX-1063]
Testing I did:
- Verified that the collapse menu still opens and closes when clicking anywhere (except on the clipboard button!) on the line with the title. 
- Verified that the clipboard button is visually in the right spot and does indeed copy stuff to your clipboard. 
https://broadworkbench.atlassian.net/browse/WX-1063?atlOrigin=eyJpIjoiY2NkNzMwNzBiNmM0NGJmODk3OWRkMTZhZTlmNDgyYzgiLCJwIjoiaiJ9
[WX-1063]: https://broadworkbench.atlassian.net/browse/WX-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Clipboard Button in Run Details

src/components/submission-common.js, src/components/submission-common.test.js
0 is also valid for Float input
Input definition passed to CBAS UI for Int input with value 0
```
"source": {
"type": "object_builder",
"fields": [
{
"name": "preemptible_tries",
"source": {
"type": "literal",
"parameter_value": 0
}
},
{
"name": "agg_preemptible_tries",
"source": {
"type": "literal",
"parameter_value": 4567
}
}
]
}
```
Closes https://broadworkbench.atlassian.net/browse/WM-1912
=> [WM-1912] 0 is a valid value for Int and Float inputs

src/pages/SubmissionDetails.js, src/pages/SubmissionDetails.test.js
Through some feedback we learned that that a "Workflow ID" isn't really useful to users most of the time. This branch simplifies a part of their experience. 
- Removed the "Workflow ID" column from the submission details table.
- Renamed "ID" to "Sample ID" for a little more clarity/familiar terminology. 
- Made the sample id a clickable hyperlink in lieu of the workflow id. 
The workflow ID will still be available from the Workflow Details page.
=> [WX-1116] Simplify Submission Details Flow

src/components/URIViewer/UriViewer.js, src/libs/ajax.js, src/pages/RunDetails.js, src/pages/RunDetails.test.js, src/pages/workspaces/workspace/jobHistory/CallTable.js
Addresses [WX-1147](https://broadworkbench.atlassian.net/browse/WX-1147)
PR fixes error message rendering on `URIViewer's` error message template when it fails to retrieve a file. This functionality is required in situations where `stdout` and `stderr` are not available because Cromwell was never able to start a task to begin with (usually due to errors like invalid/accessible docker images and/or inputs).
PR also adds tests to check against the expected functionality.
[WX-1147]: https://broadworkbench.atlassian.net/browse/WX-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WX-1147] Fix File Not Found Error template on URIViewer

public/config.json, src/components/method-common.js, src/components/method-common.test.js, src/libs/ajax-fetch.js, src/libs/ajax.js, src/pages/FindWorkflow/FindWorkflowModal.js, src/pages/FindWorkflow/FindWorkflowModal.test.js, src/pages/SubmissionConfig.js
Viewing workflow with Raw Github url source (this workflow is the pre-staged one)
Source: https://raw.githubusercontent.com/broadinstitute/viral-pipelines/v2.1.33.16/pipes/WDL/workflows/fetch_sra_to_bam.wdl
Viewing workflow with Github url source
Source: https://github.com/broadinstitute/viral-pipelines/blob/master/pipes/WDL/workflows/fetch_sra_to_bam.wdl
Viewing workflow with Dockstore source
Source: github.com/broadinstitute/viral-pipelines/fetch_sra_to_bam
Closes https://broadworkbench.atlassian.net/browse/WM-2008
=> [WM-2008] View Workflow Script modal supports viewing Dockstore and Github workflows

src/components/StructBuilder.js, src/components/StructBuilder.test.js, src/libs/mock-responses.js, src/pages/SubmissionConfig.test.js
Addressed bug by adding an `inputTableData` variable to StructBuilder analogous to that of the InputsTable, introducing the ability to modify the rows displayed to the user without altering the underlying input type and source definitions.
=> [WM-2049] Struct Input Definition Separation 

src/components/WorkflowInfoBox.js, src/fixtures/test-child-workflow.js, src/fixtures/test-parent-workflow.js, src/pages/RunDetails.js, src/pages/RunDetails.test.js, src/pages/workspaces/Breadcrumb.js, src/pages/workspaces/workspace/jobHistory/CallTable.js
Addresses [WX-1111](https://broadworkbench.atlassian.net/browse/WX-1111)
PR updates `CallTable.js` to allow for workflow exploration on Successful workflows. Feature will use existing Cromwell metadata API to query sub-workflow data as the user data dives via `View sub-workflow` button. A "breadcrumb" of the current path is rendered above the table and can be used to navigate back to previously traversed segments.
[WX-1111]: https://broadworkbench.atlassian.net/browse/WX-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WX-1111 [risk=no] Added workflow explorer to RunDetails page

src/components/InputsTable.js, src/components/InputsTable.test.js, src/components/StructBuilder.js, src/components/submission-common.js, src/components/submission-common.test.js
https://github.com/DataBiosphere/cbas-ui/assets/67511512/944b4f5e-d293-419e-90ed-e00e6c8a0447
Record lookups are only allowed to be selected from WDS attributes that match expected input types (or attributes that we can coerce, e.g. Int column provided to String input). Record lookups are also validated by this type matching, in case the user switches tables and now has records selected that exist in the new table but have a different type.
=> [WM-1961] Typecheck WDS Lookups

src/components/TroubleshootingBox.js, src/fixtures/failed-tasks.js, src/fixtures/test-child-workflow.js, src/fixtures/test-workflow.js, src/libs/ajax.js, src/pages/RunDetails.js, src/pages/RunDetails.test.js
Addresses [WX-1110](https://broadworkbench.atlassian.net/browse/WX-1110)
PR adds the front-end implementation for this ticket. This ticket will utilize the new Cromwell endpoint to fetch failed tasks for the Workflow Details page if a workflow failed. This means adding a new Ajax method to hit the new endpoint and a new processing method to format the failed task metadata for the CallTable.
[WX-1110]: https://broadworkbench.atlassian.net/browse/WX-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WX-1110] Fetch and show failed tasks for Failed Workflows on RunDetails.js

src/pages/RunDetails.js, src/pages/RunDetails.test.js
Addresses [WX-1220](https://broadworkbench.atlassian.net/browse/WX-1220)
PR wraps the request against Cromwell's `failed-tasks` endpoint in a try-catch to gracefully handle failures in situations where a workspace is using an older Cromwell version (or specifically a version that does not have the endpoint present).
[WX-1220]: https://broadworkbench.atlassian.net/browse/WX-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WX-1220] Gracefully handle failedTasks fetch on RunDetails.js
